name: oliveira_fotos
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.7.1+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  camera: ^0.8.1
  get: ^4.1.4
  # path_provider: ^1.6.24
  path_provider: ^2.0.9
  platform: ^3.1.0
  image_picker: ^0.7.4
  modal_bottom_sheet: ^2.0.1
  google_fonts: ^2.1.0
  get_storage: ^2.0.2
  sqflite: ^2.0.0+3
  dio: ^4.0.0
  flare_loading: ^3.0.0
  intl: ^0.17.0
  hand_signature: ^2.0.0
  scrollable_list_tabview: ^0.2.0-nullsafety
  flutter_native_splash: ^1.1.8+4
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  url_launcher: ^6.0.3
  cpf_cnpj_validator: ^2.0.0
  extended_masked_text: ^2.1.0
  share: ^2.0.1
  printing: ^5.6.0
  # barcode_scan2: ^4.1.3
  flutter_easyloading: ^3.0.0
  simple_animations: ^3.0.0-nullsafety.2
  # settings_ui: ^1.0.0
  settings_ui: ^2.0.2
  flutter_toggle_tab: ^1.1.1
  adonis_websok_null_safety:
    git:
      url: https://github.com/djpfs/AdonisWebsokNullSafety.git
  animated_icon_button: ^1.0.0
  direct_select_flutter: ^1.1.1
  snapping_sheet: ^3.1.0
  flutter_localizations:
    sdk: flutter
  nepali_date_picker: ^5.1.0
  flutter_datetime_picker: ^1.5.1
  dot_navigation_bar: ^1.0.1+3
  material_floating_search_bar: ^0.3.4
  pin_code_fields: ^7.3.0
  update_app: ^0.1.7
  liquid_swipe: ^2.1.0
  velocity_x: ^3.3.0
  flutter_feather_icons: ^2.0.0+1
  dropdown_selection: ^2.0.1
  dropdown_search: ^1.0.0
  rename: ^1.3.1
  sentry_flutter: ^6.5.1
  flutter_phoenix: ^1.0.0
  search_cep: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  # flutter_native_splash: ^0.2.0

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/news/
